#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Generate the Codex CLI and Gemini CLI adapters from the canonical source.

Canonical source (never edit the generated copies):
  <plugin>/skills/<skill>/SKILL.md          Agent Skills format, read natively by all three runtimes
  <plugin>/CLAUDE.md                         practice-profile template + shared guardrails
  references/jurisdictions/                  doctrine layer, all jurisdictions

Generated (this script is the only writer):
  .agents/skills/<plugin>-<skill>/           Codex repository skills (copy of the skill dir + runtime preamble)
  .agents/skills/legal-consultant-jurisdictions/   the jurisdiction tree as a skill both runtimes can read
  AGENTS.md                                  shared guardrails for Codex (it does not read plugin CLAUDE.md)
  gemini-extension/gemini-extension.json     Gemini CLI extension manifest
  gemini-extension/GEMINI.md                 same guardrails for Gemini
  gemini-extension/skills/<plugin>-<skill>/  skill copies
  gemini-extension/skills/legal-consultant-jurisdictions/
  gemini-extension/commands/<plugin>/<skill>.toml   /plugin:skill custom commands

Usage:
  python3 scripts/build-runtimes.py           # generate
  python3 scripts/build-runtimes.py --check   # exit 1 if any generated file is stale

Output is deterministic (no timestamps), so --check is a byte comparison.
"""
import filecmp
import json
import os
import re
import shutil
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PLUGINS = ["commercial-legal", "corporate-legal", "employment-legal"]
JUR_SKILL = "legal-consultant-jurisdictions"
CONFIG_PATH = "${LEGAL_CONSULTANT_HOME:-~/.legal-consultant}"

# Sections of the plugin CLAUDE.md that are shared guardrails rather than profile fields.
GUARDRAIL_SECTIONS = [
    "## Outputs", "## Decision posture on subjective legal calls", "## Shared guardrails",
    "## Scaffolding, not blinders", "## Ad-hoc questions in this domain", "## Proportionality",
    "## Jurisdiction recognition", "## Retrieved-content trust", "## Handling retrieved results",
    "## Large input", "## Large output",
]


def read(p):
    with open(p, encoding="utf-8") as f:
        return f.read()


def write(p, s):
    os.makedirs(os.path.dirname(p), exist_ok=True)
    with open(p, "w", encoding="utf-8") as f:
        f.write(s)


def marketplace_version():
    m = json.load(open(os.path.join(ROOT, ".claude-plugin", "marketplace.json"), encoding="utf-8"))
    for p in m["plugins"]:
        if p["name"] == PLUGINS[0]:
            pj = json.load(open(os.path.join(ROOT, PLUGINS[0], ".claude-plugin", "plugin.json"), encoding="utf-8"))
            return pj.get("version", "0.0.0")
    return "0.0.0"


def sections(text, wanted):
    """Return the named top-level sections of a markdown file, in file order."""
    parts = re.split(r"(?m)^(?=## )", text)
    out = []
    for part in parts:
        head = part.split("\n", 1)[0].strip()
        if head in wanted:
            out.append(part.rstrip() + "\n")
    return out


def frontmatter(text):
    m = re.match(r"---\n(.*?)\n---\n", text, flags=re.S)
    if not m:
        return {}, text
    fm = {}
    block = m.group(1)
    for key in ("name", "description", "argument-hint"):
        mm = re.search(r"(?m)^%s:\s*(.*)$" % re.escape(key), block)
        if mm:
            val = mm.group(1).strip()
            if val == ">" or val == "|":
                # block scalar: gather indented lines
                lines = []
                after = block[mm.end():].split("\n")
                for l in after[1:] if after and after[0] == "" else after:
                    if l.startswith("  "):
                        lines.append(l.strip())
                    elif l.strip() == "":
                        continue
                    else:
                        break
                val = " ".join(lines)
            fm[key] = val.strip('"')
    return fm, text[m.end():]


def preamble(runtime, plugin, skill):
    tree = (".agents/skills/%s/references/jurisdictions/" % JUR_SKILL if runtime == "codex"
            else "the `%s` skill bundled in this extension (its `references/jurisdictions/` folder)" % JUR_SKILL)
    guard = "AGENTS.md at the repo root (or your global AGENTS.md)" if runtime == "codex" else "GEMINI.md, this extension's context file"
    return (
        "> **Runtime note (generated by `scripts/build-runtimes.py`; do not edit this copy).** "
        "You are running the `%s` skill of the `%s` plugin under %s. "
        "Read the practice profile at `%s/%s/CLAUDE.md`; if it is missing, run the `%s-cold-start-interview` skill first. "
        "Every path in this skill of the form `references/jurisdictions/<code>/…` resolves to %s. "
        "The shared guardrails that the Claude Code plugin keeps in its `CLAUDE.md` are in %s and apply to every step below. "
        "Paths of the form `~/.claude/plugins/config/claude-for-legal/<plugin>/…` in upstream-inherited text mean `%s/<plugin>/…`.\n\n"
        % (skill, plugin, "OpenAI Codex CLI" if runtime == "codex" else "Gemini CLI", CONFIG_PATH, plugin,
           plugin, tree, guard, CONFIG_PATH)
    )


def build_skill_copy(runtime, plugin, skill, dest_root):
    src = os.path.join(ROOT, plugin, "skills", skill)
    dst = os.path.join(dest_root, "%s-%s" % (plugin, skill))
    shutil.copytree(src, dst, ignore=shutil.ignore_patterns(".DS_Store"))
    text = read(os.path.join(src, "SKILL.md"))
    fm, body = frontmatter(text)
    desc = fm.get("description", "").replace('"', "'")
    lines = ["---", "name: %s-%s" % (plugin, skill), 'description: "%s"' % desc]
    if fm.get("argument-hint"):
        lines.append('argument-hint: "%s"' % fm["argument-hint"].replace('"', "'"))
    lines.append("---")
    write(os.path.join(dst, "SKILL.md"), "\n".join(lines) + "\n\n" + preamble(runtime, plugin, skill) + body.lstrip("\n"))
    return desc


def build_jurisdiction_skill(dest_root):
    dst = os.path.join(dest_root, JUR_SKILL)
    shutil.copytree(os.path.join(ROOT, "references", "jurisdictions"), os.path.join(dst, "references", "jurisdictions"),
                    ignore=shutil.ignore_patterns(".DS_Store"))
    registry = read(os.path.join(ROOT, "references", "jurisdictions", "REGISTRY.md"))
    write(os.path.join(dst, "SKILL.md"),
          "---\nname: %s\ndescription: \"Doctrine reference layer for the legal-consultant skills: one folder per jurisdiction "
          "(ISO 3166-1 alpha-3 code) with MANIFEST, INDEX, SOURCES and one file per instrument. Load when any legal-consultant "
          "skill resolves a jurisdiction code, or when the user asks what a jurisdiction's rule is on a contract, corporate, "
          "or employment point.\"\n---\n\n"
          "> Generated by `scripts/build-runtimes.py` from `references/jurisdictions/`; do not edit this copy.\n\n"
          "Read `references/jurisdictions/JURISDICTION-STEP.md` for how skills use this tree, then the registry below. "
          "An unpopulated jurisdiction is a hard stop: never substitute another jurisdiction's rules or model knowledge.\n\n"
          % JUR_SKILL + registry)


def build_guardrails(runtime):
    src = read(os.path.join(ROOT, PLUGINS[0], "CLAUDE.md"))
    secs = sections(src, GUARDRAIL_SECTIONS)
    runtime_name = "OpenAI Codex CLI" if runtime == "codex" else "Gemini CLI"
    head = (
        "# Legal Consultant — shared guardrails for %s\n\n"
        "> Generated by `scripts/build-runtimes.py` from the plugin `CLAUDE.md` templates; do not edit. "
        "Regenerate with `python3 scripts/build-runtimes.py`.\n\n"
        "Legal Consultant is a jurisdiction-pluggable fork of Anthropic's `claude-for-legal`. Under Claude Code the shared guardrails "
        "live in each plugin's `CLAUDE.md`; %s does not read those files, so they are reproduced here and apply to every "
        "`commercial-legal-*`, `corporate-legal-*`, and `employment-legal-*` skill.\n\n"
        "## Runtime rules\n\n"
        "- **Practice profile path.** `%s/<plugin>/CLAUDE.md` for `commercial-legal`, `corporate-legal`, `employment-legal`, "
        "plus the shared `%s/company-profile.md`. Any text that still says `~/.claude/plugins/config/claude-for-legal/<plugin>/…` "
        "means this path. If a populated profile exists only at the old path, copy it forward once, then use the new path.\n"
        "- **Jurisdiction tree.** The `%s` skill carries `references/jurisdictions/`. Skills resolve the profile's jurisdiction "
        "codes against `REGISTRY.md` and load `<code>/MANIFEST.md`, `INDEX.md`, and the instrument files. Unpopulated code: stop.\n"
        "- **Primary-source research.** For a non-`usa` code use the portal named in the manifest, e.g. "
        "`python3 scripts/fetch-law.py --portal boe --id <guid> --lang ar` (the script is under the jurisdiction skill's "
        "`scripts/` folder when installed from this repo) or `curl` of the portal page; the built-in web-fetch tool rejects "
        "the laws.boe.gov.sa TLS chain. Tag `[BOE — Arabic]` / `[BOE — official English]`. On failure, apply the no-silent-supplement rule.\n"
        "%s"
        "- **Not available in this runtime.** Claude Code subagents (`agents/*.md`), hooks, and scheduled agents have no direct "
        "equivalent here; the scheduled behaviours (renewal watcher, leave tracker, deal debrief, playbook monitor, data-room watcher) "
        "are run on demand by invoking the matching skill. See `docs/runtime-matrix.md`.\n"
        "- **MCP servers.** Configure connectors in %s. None are required for the jurisdiction files; the upstream legal-research "
        "connectors (CourtListener, Westlaw) are only relevant when `usa` is in the footprint.\n\n"
        "## Skills\n\n"
        % (runtime_name, runtime_name, CONFIG_PATH, CONFIG_PATH, JUR_SKILL,
           ("- **Sandbox and network (Codex).** The `read-only` sandbox has no network (`CODEX_SANDBOX_NETWORK_DISABLED=1`): "
            "the fetch script and any piped `curl` fail with \"Could not resolve host\", so every research step ends in a stopped "
            "run. Run this plugin's skills with `codex exec -s workspace-write -c sandbox_workspace_write.network_access=true` "
            "(or the equivalent config). Inside the sandbox curl cannot reach the macOS Keychain, so the portal's incomplete "
            "certificate chain fails verification; `scripts/fetch-law.py` retries with the public DigiCert chain in "
            "`scripts/certs/boe-chain.pem` and succeeds. Probe the portal with a GET, never `curl -I`: the portal redirects HEAD "
            "requests into a loop.\n") if runtime == "codex" else "",
           "`~/.codex/config.toml` under `[mcp_servers.<name>]`" if runtime == "codex"
           else "`gemini-extension.json` → `mcpServers` or your `~/.gemini/settings.json`")
    )
    return head, secs


def build_all(out_root):
    version = marketplace_version()
    skills_index = []
    # Codex
    codex_skills = os.path.join(out_root, ".agents", "skills")
    for plugin in PLUGINS:
        for skill in sorted(os.listdir(os.path.join(ROOT, plugin, "skills"))):
            if not os.path.isdir(os.path.join(ROOT, plugin, "skills", skill)):
                continue
            desc = build_skill_copy("codex", plugin, skill, codex_skills)
            skills_index.append((plugin, skill, desc))
    build_jurisdiction_skill(codex_skills)
    head, secs = build_guardrails("codex")
    listing = "".join("- `$%s-%s` — %s\n" % (p, s, d.split(". ")[0][:160]) for p, s, d in skills_index)
    write(os.path.join(out_root, "AGENTS.md"), head + listing + "\n" + "\n".join(secs))
    # Gemini
    gem = os.path.join(out_root, "gemini-extension")
    gskills = os.path.join(gem, "skills")
    for plugin, skill, _ in skills_index:
        build_skill_copy("gemini", plugin, skill, gskills)
    build_jurisdiction_skill(gskills)
    head, secs = build_guardrails("gemini")
    listing = "".join("- `/%s:%s` (skill `%s-%s`) — %s\n" % (p, s, p, s, d.split(". ")[0][:160]) for p, s, d in skills_index)
    write(os.path.join(gem, "GEMINI.md"), head + listing + "\n" + "\n".join(secs))
    manifest = {
        "name": "legal-consultant",
        "version": version,
        "description": "Jurisdiction-pluggable legal assistant for commercial, corporate, and employment work (fork of claude-for-legal).",
        "contextFileName": "GEMINI.md",
    }
    write(os.path.join(gem, "gemini-extension.json"), json.dumps(manifest, indent=2) + "\n")
    for plugin, skill, desc in skills_index:
        toml = (
            'description = "%s"\n'
            'prompt = """\n'
            "Activate the `%s-%s` skill bundled in this extension and run it as written, using the practice profile at "
            "%s/%s/CLAUDE.md. User input: {{args}}\n"
            '"""\n' % (desc.replace('"', "'")[:200], plugin, skill, CONFIG_PATH, plugin)
        )
        write(os.path.join(gem, "commands", plugin, skill + ".toml"), toml)
    write(os.path.join(gem, "README.md"),
          "# legal-consultant Gemini CLI extension\n\n> Generated by `scripts/build-runtimes.py`; do not edit.\n\n"
          "Install from a local checkout: `gemini extensions install /path/to/legal-consultant/gemini-extension` "
          "(or `gemini extensions link /path/to/legal-consultant/gemini-extension` while developing).\n"
          "Install from GitHub: `gemini extensions install https://github.com/basimkhoja/legal-consultant` "
          "(the extension folder is `gemini-extension/`; if the CLI requires the manifest at the repository root, "
          "install from the local folder instead).\n\n"
          "Commands are `/commercial-legal:<skill>`, `/corporate-legal:<skill>`, `/employment-legal:<skill>`; "
          "skills are also selectable by description. Guardrails are in `GEMINI.md`.\n")


def tree_files(root):
    out = {}
    for d, _, files in os.walk(root):
        for f in files:
            if f == ".DS_Store":
                continue
            full = os.path.join(d, f)
            out[os.path.relpath(full, root)] = full
    return out


def main():
    check = "--check" in sys.argv
    targets = [".agents", "AGENTS.md", "gemini-extension"]
    if check:
        tmp = tempfile.mkdtemp(prefix="build-runtimes-")
        build_all(tmp)
        stale = []
        for t in targets:
            a, b = os.path.join(tmp, t), os.path.join(ROOT, t)
            if os.path.isdir(a):
                fa, fb = tree_files(a), tree_files(b) if os.path.isdir(b) else {}
                for rel in set(fa) | set(fb):
                    if rel not in fa or rel not in fb or not filecmp.cmp(fa[rel], fb[rel], shallow=False):
                        stale.append(os.path.join(t, rel))
            else:
                if not os.path.exists(b) or not filecmp.cmp(a, b, shallow=False):
                    stale.append(t)
        shutil.rmtree(tmp)
        if stale:
            print("stale generated files (run scripts/build-runtimes.py):\n  " + "\n  ".join(sorted(stale)[:40]))
            return 1
        print("runtime adapters are current")
        return 0
    for t in targets:
        p = os.path.join(ROOT, t)
        if os.path.isdir(p):
            shutil.rmtree(p)
        elif os.path.exists(p):
            os.remove(p)
    build_all(ROOT)
    n = sum(len(tree_files(os.path.join(ROOT, t))) for t in (".agents", "gemini-extension")) + 1
    print("generated %d files: .agents/, AGENTS.md, gemini-extension/" % n)
    return 0


if __name__ == "__main__":
    sys.exit(main())
