#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Generate INDEX.md for a jurisdiction folder from its instrument files.

Reads the "## Instrument" table of every `*.md` file in
`references/jurisdictions/<code>/` (except MANIFEST, INDEX, SOURCES) and writes
`INDEX.md` with one row per file: instrument, issuing instrument, effective
date, text last read, official source, rule-row count, and how many rows carry
each provenance tag. Also validates that every rule row carries exactly one
allowed tag, and exits 1 if not, so an untagged rule cannot ship.

Usage: python3 scripts/build-jurisdiction-index.py <code> [--check]
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SKIP = {"MANIFEST.md", "INDEX.md", "SOURCES.md"}
SETTLED = re.compile(r"\[settled — last confirmed \d{4}-\d{2}-\d{2}\]")
MODEL = re.compile(r"\[model knowledge — verify\]")


def field(table, name):
    m = re.search(r"^\|\s*" + re.escape(name) + r"\s*\|\s*(.*?)\s*\|\s*$", table, flags=re.M)
    return m.group(1).strip() if m else ""


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        return 2
    code = sys.argv[1]
    check = "--check" in sys.argv
    folder = os.path.join(ROOT, "references", "jurisdictions", code)
    rows, problems = [], []
    for f in sorted(os.listdir(folder)):
        if not f.endswith(".md") or f in SKIP or f.startswith("_"):
            continue
        text = open(os.path.join(folder, f), encoding="utf-8").read()
        inst = re.search(r"## Instrument\n(.*?)\n## ", text, flags=re.S)
        if not inst:
            continue  # not an instrument file (e.g. playbook-defaults.md)
        table = inst.group(1)
        rules = re.search(r"## Rules\n(.*?)\n## ", text, flags=re.S)
        body = rules.group(1) if rules else ""
        rule_rows = []
        for l in body.splitlines():
            if not l.startswith("|") or l.startswith("|--") or l.startswith("|---"):
                continue
            cells = [c.strip() for c in l.strip().strip("|").split("|")]
            if len(cells) < 5 or cells[0] in ("Article", "Entity type"):
                continue
            rule_rows.append(cells)
        # Provenance is judged on the Tag column (last cell) only; inline flags in
        # Practical effect are allowed and do not change the row's tag.
        n_settled = n_model = 0
        for cells in rule_rows:
            tag = cells[-1]
            s, m = bool(SETTLED.search(tag)), bool(MODEL.search(tag))
            if s and not m:
                n_settled += 1
            elif m:
                n_model += 1  # a split tag counts as model-knowledge, the conservative reading
            else:
                problems.append(f"{f}: rule row with no provenance tag in the Tag column: {' | '.join(cells)[:90]}")
        title = re.match(r"# (.+)", text)
        rows.append({
            "file": f,
            "title": title.group(1).strip() if title else f,
            "decree": field(table, "Issuing instrument"),
            "effective": field(table, "Effective date"),
            "read": field(table, "Text last read from the official source"),
            "source": field(table, "Official source (authoritative language)"),
            "n": len(rule_rows), "settled": n_settled, "model": n_model,
        })
    out = [f"# Index: {code}\n",
           "Generated by `scripts/build-jurisdiction-index.py`; do not edit by hand. One row per instrument file. "
           "\"Settled\" counts rule rows tagged `[settled — last confirmed YYYY-MM-DD]` (primary text read on that date); "
           "\"Model\" counts rows whose Tag column carries `[model knowledge — verify]` (a split tag counts here). Inline flags inside a Practical effect cell do not change the row's tag.\n",
           "| File | Instrument | Issuing instrument | Effective | Text last read | Rules | Settled | Model | Source |\n",
           "|---|---|---|---|---|---|---|---|---|\n"]
    for r in rows:
        src = r["source"]
        src_md = f"[link]({src.split()[0]})" if src.startswith("http") else src
        out.append(f"| `{r['file']}` | {r['title']} | {r['decree']} | {r['effective']} | {r['read']} | {r['n']} | {r['settled']} | {r['model']} | {src_md} |\n")
    tot = sum(r["n"] for r in rows)
    out.append(f"\n**Totals:** {len(rows)} instrument files, {tot} rule rows, {sum(r['settled'] for r in rows)} settled, {sum(r['model'] for r in rows)} model-knowledge.\n")
    index_path = os.path.join(folder, "INDEX.md")
    if check:
        current = open(index_path, encoding="utf-8").read() if os.path.exists(index_path) else ""
        if current != "".join(out):
            problems.append("INDEX.md is stale; run scripts/build-jurisdiction-index.py " + code)
    else:
        open(index_path, "w", encoding="utf-8").write("".join(out))
        print(f"wrote {index_path}: {len(rows)} files, {tot} rule rows")
    if problems:
        print("\n".join(problems))
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
